# cargo-deny configuration

[licenses]
# List of explicitly allowed licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause", 
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "Unicode-3.0",
    "CC0-1.0",
    "Unlicense",
]
# Deny unlicensed dependencies
unlicensed = "deny"
# Warn about copyleft licenses
copyleft = "warn"

[bans]
# Lint level for when multiple versions of the same dependency are detected
multiple-versions = "warn"
# Allow wildcard dependencies
wildcards = "allow"
# Highlight all duplicate dependencies
highlight = "all"

[advisories]
# Path to the advisory database
db-path = "~/.cargo/advisory-db"
# URL(s) to the advisory database
db-urls = ["https://github.com/rustsec/advisory-db"]
# Deny crates with security vulnerabilities
vulnerability = "deny"
# Warn for unmaintained crates
unmaintained = "warn"
# Warn for crates that have been yanked from crates.io
yanked = "warn"
# Warn about informational notices
notice = "warn"
# Ignore specific advisories
ignore = []

[sources]
# Warn about unknown registries
unknown-registry = "warn"
# Warn about unknown git sources
unknown-git = "warn"
# Allow git sources
allow-git = []